name: CI - Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Build da imagem Docker
      run: docker build -t simple-node-status-dev .

    - name: Subir container em background
      run: docker run -d -p 3000:3000 --name status-dev simple-node-status-dev

    - name: Aguardar a aplicação subir
      run: sleep 10

    - name: Testar endpoint /status
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/status)
        if [ "$STATUS" != "200" ]; then
          echo "Erro: status da aplicação é $STATUS"
          exit 1
        fi

    - name: Parar e remover o container
      run: docker rm -f status-dev