name: CI/CD - Desenvolvimento

on:
  push:
    branches: [ develop ]

jobs:
  build-test-deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build da imagem Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-node-status:dev .

    - name: Push da imagem
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-node-status:dev
