name: CI/CD - Production

on:
  push:
    branches:
      - main

jobs:
  build-test-push-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Build da imagem Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-node-status:latest .

    - name: Subir container em background
      run: docker run -d -p 3000:3000 --name status-prod ${{ secrets.DOCKER_USERNAME }}/simple-node-status:latest

    - name: Aguardar a aplicação subir
      run: sleep 5

    - name: Testar endpoint /status
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/status)
        if [ "$STATUS" != "200" ]; then
          echo "Erro: status da aplicação é $STATUS"
          exit 1
        fi

    - name: Parar e remover o container
      run: docker rm -f status-prod

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push para o Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-node-status:latest
